# Generated by Django 5.1.7 on 2026-08-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_branch_user_role_user_branch_sector_branch_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('general_manager', 'Responsable général'), ('sector_manager', 'Responsable de secteur'), ('user', ' utilisateur')], default='user', max_length=20),
        ),
    ]
