# Generated by Django 5.1.7 on 2026-08-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_evaluation_filiale_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datedim',
            options={'ordering': ['annee', 'mois']},
        ),
        migrations.AlterModelOptions(
            name='laboratoire',
            options={},
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='month',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='year',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='filiale_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='moy_ponderation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='tx_conformite',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
