# Generated by Django 5.1.7 on 2026-08-07 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_datedim_options_alter_laboratoire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='laboratoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='user.laboratoire'),
        ),
    ]
