# Generated by Django 5.1.7 on 2026-08-10 12:36

import django.db.models.deletion
from django.db import migrations, models


def backfill_user_sector(apps, schema_editor):
    User = apps.get_model('user', 'User')
    Branch = apps.get_model('user', 'Branch')
    Sector = apps.get_model('user', 'Sector')

    branch_sector_map = {
        branch.id: branch.sector_id
        for branch in Branch.objects.all().only('id', 'sector_id')
    }
    managed_sector_by_manager = {
        sector.manager_id: sector.id
        for sector in Sector.objects.exclude(manager_id__isnull=True).only('id', 'manager_id')
    }

    for user in User.objects.all().only('id', 'role', 'branch_id', 'sector_id'):
        sector_id = None
        if user.role == 'sector_manager':
            sector_id = managed_sector_by_manager.get(user.id)
        elif user.role == 'user' and user.branch_id:
            sector_id = branch_sector_map.get(user.branch_id)

        if user.sector_id != sector_id:
            User.objects.filter(pk=user.pk).update(sector_id=sector_id)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_drop_legacy_evaluation_laboratoire_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user.sector'),
        ),
        migrations.RunPython(backfill_user_sector, migrations.RunPython.noop),
    ]
