from django.urls import path
from .views import (
    register,
    login_view,
    logout_view,
    chatbot_reply,
    admin_login,
    admin_users,
    admin_user_detail,
    admin_toggle_user,
    scope,
    admin_branches,
    admin_branch_detail,
    admin_branch_change_sector,
    admin_sectors,
    admin_sector_detail,
    admin_evaluations,
    admin_evaluation_detail,
    admin_laboratoires,
    admin_laboratoire_detail,
    evaluations_list,
    evaluations_overview,
    evaluations_session,
    evaluations_summary,
    user_evaluations,
    user_evaluation_detail,
    user_evaluations_overview,
    user_evaluations_summary,
    user_evaluations_session,
    user_profile,
    user_password,
    checklist_template,
    ml_predict,
    ml_status,
)

urlpatterns = [
    path('register/', register),
    path('login/', login_view),
    path('logout/', logout_view),
    path('chatbot/', chatbot_reply),
    path('scope/', scope),
    path('admin/login/', admin_login),
    path('admin/users/', admin_users),
    path('admin/users/<int:user_id>/', admin_user_detail),
    path('admin/users/<int:user_id>/toggle/', admin_toggle_user),
    path('admin/branches/', admin_branches),
    path('admin/branches/<int:branch_id>/', admin_branch_detail),
    path('admin/branches/<int:branch_id>/change-sector/', admin_branch_change_sector),
    path('admin/sectors/', admin_sectors),
    path('admin/sectors/<int:sector_id>/', admin_sector_detail),
    path('admin/evaluations/', admin_evaluations),
    path('admin/evaluations/<int:evaluation_id>/', admin_evaluation_detail),
    path('admin/laboratoires/', admin_laboratoires),
    path('admin/laboratoires/<int:laboratoire_id>/', admin_laboratoire_detail),
    path('evaluations/', evaluations_list),
    path('evaluations-overview/', evaluations_overview),
    path('evaluations-summary/', evaluations_summary),
    path('evaluations-session/', evaluations_session),
    path('user/evaluations/', user_evaluations),
    path('user/evaluations/<int:evaluation_id>/', user_evaluation_detail),
    path('user/evaluations-overview/', user_evaluations_overview),
    path('user/evaluations-summary/', user_evaluations_summary),
    path('user/evaluations-session/', user_evaluations_session),
    path('user/profile/', user_profile),
    path('user/password/', user_password),
    path('user/checklist-template/', checklist_template),
    path('ml/predict/', ml_predict),
    path('ml/status/', ml_status),
]
